/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFileresourceModal: typeof import('./components/modals/AddFileresourceModal.vue')['default']
    AddFileresourceTypeModal: typeof import('./components/modals/AddFileresourceTypeModal.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AsyncSidebar: typeof import('./components/structure/AsyncSidebar.vue')['default']
    AttributeDetails: typeof import('./components/widgets/AttributeDetails.vue')['default']
    BarChart: typeof import('./components/charts/BarChart.vue')['default']
    BaseChart: typeof import('./components/charts/BaseChart.vue')['default']
    BaseTable: typeof import('./components/tables/BaseTable.vue')['default']
    ChangelogInfo: typeof import('./components/widgets/ChangelogInfo.vue')['default']
    CollaboratorDetails: typeof import('./components/widgets/CollaboratorDetails.vue')['default']
    CollaboratorTable: typeof import('./components/tables/CollaboratorTable.vue')['default']
    ColorGradient: typeof import('./components/widgets/ColorGradient.vue')['default']
    ConfirmModal: typeof import('./components/modals/ConfirmModal.vue')['default']
    copy: typeof import('./components/tables/MarkerTable copy.vue')['default']
    DatasetAttributeTable: typeof import('./components/tables/DatasetAttributeTable.vue')['default']
    Datasets: typeof import('./components/widgets/Datasets.vue')['default']
    DatasetTable: typeof import('./components/tables/DatasetTable.vue')['default']
    DropFilePreview: typeof import('./components/widgets/DropFilePreview.vue')['default']
    ExifInfo: typeof import('./components/widgets/ExifInfo.vue')['default']
    ExperimentTable: typeof import('./components/tables/ExperimentTable.vue')['default']
    FileResourceTable: typeof import('./components/tables/FileResourceTable.vue')['default']
    GenericAddEditFormModal: typeof import('./components/modals/GenericAddEditFormModal.vue')['default']
    GermplasmTable: typeof import('./components/tables/GermplasmTable.vue')['default']
    GroupTable: typeof import('./components/tables/GroupTable.vue')['default']
    HtmlTemplateEditor: typeof import('./components/widgets/HtmlTemplateEditor.vue')['default']
    ImageCarousel: typeof import('./components/structure/ImageCarousel.vue')['default']
    ImageTable: typeof import('./components/tables/ImageTable.vue')['default']
    ImageTags: typeof import('./components/widgets/ImageTags.vue')['default']
    InstitutionTable: typeof import('./components/tables/InstitutionTable.vue')['default']
    LicenseModal: typeof import('./components/modals/LicenseModal.vue')['default']
    LocationMap: typeof import('./components/map/LocationMap.vue')['default']
    LocationTable: typeof import('./components/tables/LocationTable.vue')['default']
    LoginModal: typeof import('./components/modals/LoginModal.vue')['default']
    LoginSection: typeof import('./components/widgets/LoginSection.vue')['default']
    MainComponent: typeof import('./components/structure/MainComponent.vue')['default']
    MainNavigation: typeof import('./components/structure/MainNavigation.vue')['default']
    MarkerTable: typeof import('./components/tables/MarkerTable.vue')['default']
    ProjectTable: typeof import('./components/tables/ProjectTable.vue')['default']
    PublicationCard: typeof import('./components/cards/PublicationCard.vue')['default']
    Publications: typeof import('./components/widgets/Publications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableFilterModal: typeof import('./components/modals/TableFilterModal.vue')['default']
    TaxonomySunburst: typeof import('./components/charts/TaxonomySunburst.vue')['default']
    TaxonomyTable: typeof import('./components/tables/TaxonomyTable.vue')['default']
    TaxonomyTreemap: typeof import('./components/charts/TaxonomyTreemap.vue')['default']
    UserDropdown: typeof import('./components/structure/UserDropdown.vue')['default']
  }
}
