/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<
      'home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/cookie': RouteRecordInfo<
      '/about/cookie',
      '/about/cookie',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'aboutExportFormats': RouteRecordInfo<
      'aboutExportFormats',
      '/about/export-formats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'aboutGerminate': RouteRecordInfo<
      'aboutGerminate',
      '/about/germinate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'aboutProject': RouteRecordInfo<
      'aboutProject',
      '/about/project',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'backup': RouteRecordInfo<
      'backup',
      '/admin/settings/backup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'germinateSettings': RouteRecordInfo<
      'germinateSettings',
      '/admin/settings/germinate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'userPermissions': RouteRecordInfo<
      'userPermissions',
      '/admin/user/permissions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'climates': RouteRecordInfo<
      'climates',
      '/data/climate/climates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'climateDetails': RouteRecordInfo<
      'climateDetails',
      '/data/climate/climates/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'climateOverview': RouteRecordInfo<
      'climateOverview',
      '/data/climate/overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dataResources': RouteRecordInfo<
      'dataResources',
      '/data/data-resources',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'datasets': RouteRecordInfo<
      'datasets',
      '/data/datasets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'datasetDetails': RouteRecordInfo<
      'datasetDetails',
      '/data/datasets/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'experiments': RouteRecordInfo<
      'experiments',
      '/data/experiments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'export': RouteRecordInfo<
      'export',
      '/data/export/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'exportClimates': RouteRecordInfo<
      'exportClimates',
      '/data/export/climate/:datasetIds',
      { datasetIds: ParamValue<true> },
      { datasetIds: ParamValue<false> },
      | never
    >,
    'exportGenotypes': RouteRecordInfo<
      'exportGenotypes',
      '/data/export/genotype/:datasetIds',
      { datasetIds: ParamValue<true> },
      { datasetIds: ParamValue<false> },
      | never
    >,
    'exportPedigrees': RouteRecordInfo<
      'exportPedigrees',
      '/data/export/pedigree/:datasetIds',
      { datasetIds: ParamValue<true> },
      { datasetIds: ParamValue<false> },
      | never
    >,
    'exporTrials': RouteRecordInfo<
      'exporTrials',
      '/data/export/trials/:datasetIds',
      { datasetIds: ParamValue<true> },
      { datasetIds: ParamValue<false> },
      | never
    >,
    'genesysRequest': RouteRecordInfo<
      'genesysRequest',
      '/data/genesys-request',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'maps': RouteRecordInfo<
      'maps',
      '/data/genotypes/maps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'mapDetails': RouteRecordInfo<
      'mapDetails',
      '/data/genotypes/maps/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'markers': RouteRecordInfo<
      'markers',
      '/data/genotypes/markers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'markerDetails': RouteRecordInfo<
      'markerDetails',
      '/data/genotypes/markers/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'genotypes': RouteRecordInfo<
      'genotypes',
      '/data/genotypes/overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'geographicSearch': RouteRecordInfo<
      'geographicSearch',
      '/data/geography/geographic-search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'locations': RouteRecordInfo<
      'locations',
      '/data/geography/locations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'germplasm': RouteRecordInfo<
      'germplasm',
      '/data/germplasm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'passport': RouteRecordInfo<
      'passport',
      '/data/germplasm/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/data/germplasm/germplasm-match': RouteRecordInfo<
      '/data/germplasm/germplasm-match',
      '/data/germplasm/germplasm-match',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'germplasmUnifier': RouteRecordInfo<
      'germplasmUnifier',
      '/data/germplasm/unify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'pedigrees': RouteRecordInfo<
      'pedigrees',
      '/data/pedigrees',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'statistics': RouteRecordInfo<
      'statistics',
      '/data/statistics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dataStories': RouteRecordInfo<
      'dataStories',
      '/data/stories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'taxonomies': RouteRecordInfo<
      'taxonomies',
      '/data/taxonomies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'taxonomyProviderDetails': RouteRecordInfo<
      'taxonomyProviderDetails',
      '/data/taxonomies/:id/providers',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'trials': RouteRecordInfo<
      'trials',
      '/data/trials/overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'traits': RouteRecordInfo<
      'traits',
      '/data/trials/traits',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'traitDetails': RouteRecordInfo<
      'traitDetails',
      '/data/trials/traits/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'importUpload': RouteRecordInfo<
      'importUpload',
      '/data/upload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'groups': RouteRecordInfo<
      'groups',
      '/groups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'groupDetails': RouteRecordInfo<
      'groupDetails',
      '/groups/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'images': RouteRecordInfo<
      'images',
      '/images',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'markedItems': RouteRecordInfo<
      'markedItems',
      '/marked-items',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'markedItemType': RouteRecordInfo<
      'markedItemType',
      '/marked-items/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'projects': RouteRecordInfo<
      'projects',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'projectDetails': RouteRecordInfo<
      'projectDetails',
      '/projects/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'publications': RouteRecordInfo<
      'publications',
      '/publications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'publicationDetails': RouteRecordInfo<
      'publicationDetails',
      '/publications/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'search': RouteRecordInfo<
      'search',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'searchQuery': RouteRecordInfo<
      'searchQuery',
      '/search/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'home'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/about/cookie.vue': {
      routes:
        | '/about/cookie'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/about/export-formats.vue': {
      routes:
        | 'aboutExportFormats'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/about/germinate.vue': {
      routes:
        | 'aboutGerminate'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/about/project.vue': {
      routes:
        | 'aboutProject'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/settings/backup.vue': {
      routes:
        | 'backup'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/settings/germinate.vue': {
      routes:
        | 'germinateSettings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/user/permissions.vue': {
      routes:
        | 'userPermissions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/climate/climates/index.vue': {
      routes:
        | 'climates'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/climate/climates/[id].vue': {
      routes:
        | 'climateDetails'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/data/climate/overview.vue': {
      routes:
        | 'climateOverview'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/data-resources.vue': {
      routes:
        | 'dataResources'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/datasets/index.vue': {
      routes:
        | 'datasets'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/datasets/[id].vue': {
      routes:
        | 'datasetDetails'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/data/experiments.vue': {
      routes:
        | 'experiments'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/export/[id].vue': {
      routes:
        | 'export'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/data/export/climate/[datasetIds].vue': {
      routes:
        | 'exportClimates'
      views:
        | never
      pathParamNames:
        | 'datasetIds'
    }
    'src/pages/data/export/genotype/[datasetIds].vue': {
      routes:
        | 'exportGenotypes'
      views:
        | never
      pathParamNames:
        | 'datasetIds'
    }
    'src/pages/data/export/pedigree/[datasetIds].vue': {
      routes:
        | 'exportPedigrees'
      views:
        | never
      pathParamNames:
        | 'datasetIds'
    }
    'src/pages/data/export/trials/[datasetIds].vue': {
      routes:
        | 'exporTrials'
      views:
        | never
      pathParamNames:
        | 'datasetIds'
    }
    'src/pages/data/genesys-request.vue': {
      routes:
        | 'genesysRequest'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/genotypes/maps/index.vue': {
      routes:
        | 'maps'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/genotypes/maps/[id].vue': {
      routes:
        | 'mapDetails'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/data/genotypes/markers/index.vue': {
      routes:
        | 'markers'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/genotypes/markers/[id].vue': {
      routes:
        | 'markerDetails'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/data/genotypes/overview.vue': {
      routes:
        | 'genotypes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/geography/geographic-search.vue': {
      routes:
        | 'geographicSearch'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/geography/locations.vue': {
      routes:
        | 'locations'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/germplasm/index.vue': {
      routes:
        | 'germplasm'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/germplasm/[id].vue': {
      routes:
        | 'passport'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/data/germplasm/germplasm-match.vue': {
      routes:
        | '/data/germplasm/germplasm-match'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/germplasm/unify.vue': {
      routes:
        | 'germplasmUnifier'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/pedigrees/index.vue': {
      routes:
        | 'pedigrees'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/statistics.vue': {
      routes:
        | 'statistics'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/stories/index.vue': {
      routes:
        | 'dataStories'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/taxonomies/index.vue': {
      routes:
        | 'taxonomies'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/taxonomies/[id]/providers.vue': {
      routes:
        | 'taxonomyProviderDetails'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/trials/overview.vue': {
      routes:
        | 'trials'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/trials/traits/index.vue': {
      routes:
        | 'traits'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/data/trials/traits/[id].vue': {
      routes:
        | 'traitDetails'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/data/upload.vue': {
      routes:
        | 'importUpload'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/groups/index.vue': {
      routes:
        | 'groups'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/groups/[id].vue': {
      routes:
        | 'groupDetails'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/images/index.vue': {
      routes:
        | 'images'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | 'login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/marked-items/index.vue': {
      routes:
        | 'markedItems'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/marked-items/[id].vue': {
      routes:
        | 'markedItemType'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/projects/index.vue': {
      routes:
        | 'projects'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[id].vue': {
      routes:
        | 'projectDetails'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/publications/index.vue': {
      routes:
        | 'publications'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/publications/[id].vue': {
      routes:
        | 'publicationDetails'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/search/index.vue': {
      routes:
        | 'search'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/search/[id].vue': {
      routes:
        | 'searchQuery'
      views:
        | never
      pathParamNames:
        | 'id'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
