/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about/export-formats': RouteRecordInfo<'/about/export-formats', '/about/export-formats', Record<never, never>, Record<never, never>>,
    '/about/germinate': RouteRecordInfo<'/about/germinate', '/about/germinate', Record<never, never>, Record<never, never>>,
    '/about/project': RouteRecordInfo<'/about/project', '/about/project', Record<never, never>, Record<never, never>>,
    '/admin/settings/backup': RouteRecordInfo<'/admin/settings/backup', '/admin/settings/backup', Record<never, never>, Record<never, never>>,
    '/data/climate/climates': RouteRecordInfo<'/data/climate/climates', '/data/climate/climates', Record<never, never>, Record<never, never>>,
    '/data/data-resources': RouteRecordInfo<'/data/data-resources', '/data/data-resources', Record<never, never>, Record<never, never>>,
    '/data/datasets/': RouteRecordInfo<'/data/datasets/', '/data/datasets', Record<never, never>, Record<never, never>>,
    '/data/datasets/[id]': RouteRecordInfo<'/data/datasets/[id]', '/data/datasets/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/data/experiments': RouteRecordInfo<'/data/experiments', '/data/experiments', Record<never, never>, Record<never, never>>,
    '/data/genesys-request': RouteRecordInfo<'/data/genesys-request', '/data/genesys-request', Record<never, never>, Record<never, never>>,
    '/data/genotypes/maps/': RouteRecordInfo<'/data/genotypes/maps/', '/data/genotypes/maps', Record<never, never>, Record<never, never>>,
    '/data/genotypes/maps/[id]': RouteRecordInfo<'/data/genotypes/maps/[id]', '/data/genotypes/maps/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/data/genotypes/markers/': RouteRecordInfo<'/data/genotypes/markers/', '/data/genotypes/markers', Record<never, never>, Record<never, never>>,
    '/data/genotypes/markers/[id]': RouteRecordInfo<'/data/genotypes/markers/[id]', '/data/genotypes/markers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/data/geography/geographic-search': RouteRecordInfo<'/data/geography/geographic-search', '/data/geography/geographic-search', Record<never, never>, Record<never, never>>,
    '/data/geography/locations': RouteRecordInfo<'/data/geography/locations', '/data/geography/locations', Record<never, never>, Record<never, never>>,
    '/data/germplasm/': RouteRecordInfo<'/data/germplasm/', '/data/germplasm', Record<never, never>, Record<never, never>>,
    '/data/germplasm/[id]': RouteRecordInfo<'/data/germplasm/[id]', '/data/germplasm/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/data/statistics': RouteRecordInfo<'/data/statistics', '/data/statistics', Record<never, never>, Record<never, never>>,
    '/data/taxonomies/': RouteRecordInfo<'/data/taxonomies/', '/data/taxonomies', Record<never, never>, Record<never, never>>,
    '/data/taxonomies/[id]/providers': RouteRecordInfo<'/data/taxonomies/[id]/providers', '/data/taxonomies/:id/providers', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/data/trials/traits/': RouteRecordInfo<'/data/trials/traits/', '/data/trials/traits', Record<never, never>, Record<never, never>>,
    '/data/trials/traits/[id]': RouteRecordInfo<'/data/trials/traits/[id]', '/data/trials/traits/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/groups/': RouteRecordInfo<'/groups/', '/groups', Record<never, never>, Record<never, never>>,
    '/groups/[id]': RouteRecordInfo<'/groups/[id]', '/groups/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/images/': RouteRecordInfo<'/images/', '/images', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/marked-items/': RouteRecordInfo<'/marked-items/', '/marked-items', Record<never, never>, Record<never, never>>,
    '/marked-items/[id]': RouteRecordInfo<'/marked-items/[id]', '/marked-items/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/projects/[id]': RouteRecordInfo<'/projects/[id]', '/projects/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/search/': RouteRecordInfo<'/search/', '/search', Record<never, never>, Record<never, never>>,
    '/search/[id]': RouteRecordInfo<'/search/[id]', '/search/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
